src/Sistema/FACTURACIONBundle/Entity/FacturaVenta.php
<?php

namespace Sistema\FACTURACIONBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * FacturaVenta
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Sistema\FACTURACIONBundle\Entity\FacturaVentaRepository")
 * @UniqueEntity("numero")
 */
class FacturaVenta extends Comprobante {

    protected $discriminador;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="numero", type="integer")
     * @Assert\NotNull()
     */
    protected $numero;

    /**
     * @var string
     *
     * @ORM\Column(name="tipo", type="string", length=1)
     * @Assert\Choice(
     *     choices = { "A", "B" ,"I"},
     *     message = "solo factura tipo A o B."
     * )
     */
    protected $tipo;

    /**
     * Constructor
     */
    public function __construct() {
        $this->fecha = new \DateTime('now');  
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set numero
     *
     * @param  integer      $numero
     * @return FacturaVenta
     */
    public function setNumero($numero) {
        $this->numero = $numero;

        return $this;
    }

    /**
     * Get numero
     *
     * @return integer
     */
    public function getNumero() {
        return $this->numero;
    }

    /**
     * Set tipo
     *
     * @param  string      $tipo
     * @return FacturaVenta
     */
    public function setTipo($tipo) {
        $this->tipo = $tipo;

        return $this;
    }

    /**
     * Get tipo
     *
     * @return string
     */
    public function getTipo() {
        return $this->tipo;
    }

    /**
     * Set fecha
     *
     * @param  \DateTime    $fecha
     * @return FacturaVenta
     */
    public function setFecha($fecha) {
        $this->fecha = $fecha;

        return $this;
    }

    /**
     * Get fecha
     *
     * @return \DateTime
     */
    public function getFecha() {
        return $this->fecha;
    }

    /**
     * Set descripcion
     *
     * @param  string       $descripcion
     * @return FacturaVenta
     */
    public function setDescripcion($descripcion) {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get descripcion
     *
     * @return string
     */
    public function getDescripcion() {
        return $this->descripcion;
    }

    /**
     * Get descripcion
     *
     * @return string
     */
    public function getOrdenDescripcion() {
        return "OT nro. " . $this->getOrden() . " | " . $this->descripcion;
    }

    /**
     * Set monto
     *
     * @param  float        $monto
     * @return FacturaVenta
     */
    public function setMonto($monto) {
        $this->monto = $monto;

        return $this;
    }

    /**
     * Get monto
     *
     * @return float
     */
    public function getMonto() {
        return $this->monto;
    }

    /**
     * Set iva
     *
     * @param  float        $iva
     * @return FacturaVenta
     */
    public function setIva($iva) {
        $this->iva = $iva;

        return $this;
    }

    /**
     * Get iva
     *
     * @return float
     */
    public function getIva() {
        return $this->iva;
    }

    /**
     * Set anulado
     *
     * @param  boolean      $anulado
     * @return FacturaVenta
     */
    public function setAnulado($anulado) {
        $this->anulado = $anulado;

        return $this;
    }

    /**
     * Get anulado
     *
     * @return boolean
     */
    public function getAnulado() {
        return $this->anulado;
    }

    /**
     * Set formaPago
     *
     * @param  string       $formaPago
     * @return FacturaVenta
     */
    public function setFormaPago($formaPago) {
        $this->formaPago = $formaPago;

        return $this;
    }

    /**
     * Get formaPago
     *
     * @return string
     */
    public function getFormaPago() {
        return $this->formaPago;
    }

    /**
     * Set orden
     *
     * @param  \Sistema\STOCKBundle\Entity\Orden $orden
     * @return FacturaVenta
     */
    public function setOrden(\Sistema\STOCKBundle\Entity\Orden $orden = null) {
        $this->orden = $orden;

        return $this;
    }

    /**
     * Get orden
     *
     * @return \Sistema\STOCKBundle\Entity\Orden
     */
    public function getOrden() {
        return $this->orden;
    }
}

src/Sistema/FACTURACIONBundle/Controller/FacturaVentaController.php
<?php

namespace Sistema\FACTURACIONBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sistema\FACTURACIONBundle\Entity\FacturaVenta;
use Sistema\FACTURACIONBundle\Form\FacturaVentaType;
use Sistema\FACTURACIONBundle\Form\FacturaVentaFilterType;
use Sistema\FACTURACIONBundle\Entity\Asiento;

/**
 * FacturaVenta controller.
 * @author Nombre Apellido <name@gmail.com>
 *
 * @Route("/admin/facturaventa")
 */
class FacturaVentaController extends Controller {
    /**
     * Lists all FacturaVenta entities.
     *
     * @Route("/", name="admin_facturaventa")
     * @Method("GET")
     * @Template()
     */
    public function indexAction() {
        $this->get('security_role')->controlRolesUser();
        list($filterForm, $queryBuilder) = $this->filter();

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $queryBuilder,
            $this->get('request')->query->get('page', 1),
            (isset($this->container->parameters['knp_paginator.page_range'])) ? $this->container->parameters['knp_paginator.page_range'] : 10
        );

        return array(
            'entities'   => $pagination,
            'filterForm' => $filterForm->createView(),
        );
    }

    /**
     * Process filter request.
     *
     * @return array
     */
    protected function filter() {
        $request = $this->getRequest();
        $session = $request->getSession();
        $filterForm = $this->createFilterForm();
        $em = $this->getDoctrine()->getManager();
        $queryBuilder = $em->getRepository('SistemaFACTURACIONBundle:FacturaVenta')
                ->createQueryBuilder('a')
                ->orderBy('a.id', 'DESC')
        ;
        // Bind values from the request
        $filterForm->handleRequest($request);
        // Reset filter
        if ($filterForm->get('reset')->isClicked()) {
            $session->remove('FacturaVentaControllerFilter');
            $filterForm = $this->createFilterForm();
        }

        // Filter action
        if ($filterForm->get('filter')->isClicked()) {
            if ($filterForm->isValid()) {
                // Build the query from the given form object
                $this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($filterForm, $queryBuilder);
                // Save filter to session
                $filterData = $filterForm->getData();
                $session->set('FacturaVentaControllerFilter', $filterData);
            }
        } else {
            // Get filter from session
            if ($session->has('FacturaVentaControllerFilter')) {
                $filterData = $session->get('FacturaVentaControllerFilter');
                $filterForm = $this->createFilterForm($filterData);
                $this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($filterForm, $queryBuilder);
            }
        }

        return array($filterForm, $queryBuilder);
    }

    /**
     * Create filter form.
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createFilterForm($filterData = null) {
        $form = $this->createForm(new FacturaVentaFilterType(), $filterData, array(
            'action' => $this->generateUrl('admin_facturaventa'),
            'method' => 'GET',
        ));

        $form
            ->add('filter', 'submit', array(
                'translation_domain' => 'MWSimpleCrudGeneratorBundle',
                'label' => 'views.index.filter',
                'attr' => array('class' => 'btn btn-success col-lg-1'),
            ))
            ->add('reset', 'submit', array(
                'translation_domain' => 'MWSimpleCrudGeneratorBundle',
                'label' => 'views.index.reset',
                'attr' => array('class' => 'btn btn-danger col-lg-1 col-lg-offset-1'),
            ))
        ;

        return $form;
    }

    /**
     * Creates a new FacturaVenta entity.
     *
     * @Route("/", name="admin_facturaventa_create")
     * @Method("POST")
     * @Template("SistemaFACTURACIONBundle:FacturaVenta:new.html.twig")
     */
    public function createAction(Request $request) {
        $this->get('security_role')->controlRolesUser();
        $entity = new FacturaVenta();
        //agrego cuentas segun proceso
        $proceso = $request->request->get('sistema_facturacionbundle_facturaventa')['proceso'];
        $procesoService = $this->get('proceso');
        $entityProceso  = $procesoService->create($entity, $proceso);
        $entity->setProceso($entityProceso);
        //fin agrego
        $form   = $this->createCreateForm($entity);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            //MODIFICACION DE FECHA FORM
            $fecha = $entity->getFecha()->format('Y-m-d');
            $time = new \DateTime('now');
            //agrego a la fecha del form el time
            $newFecha = $fecha . ' ' . $time->format('H:i:s');
            $newDateTimeNow = new \DateTime();
            $newDateTimeNow->createFromFormat('Y-m-d H:i:s', $newFecha);
            //seteo la fecha con su time
            $entity->setFecha($newDateTimeNow);
            //FIN MODIFICACION DE FECHA FORM
            $servicioCuenta = $this->get('actualizarCuentas');
            $servicioCuenta->creaAsientos($entity, "cliente");
            //Si es ROLE_ADMIN entra y si hay mas de 1 caja abierta por usuario las trae a todas.
            if ($this->get('security.context')->isGranted('ROLE_ADMIN')) {
                $cajaAbierta = $em->getRepository('SistemaFACTURACIONBundle:Caja')
                    ->findCajaAbierta();
            } else {
                $cajaAbierta = $em->getRepository('SistemaFACTURACIONBundle:Caja')
                    ->findCajaAbierta($this->getUser()->getId());
            }
            //Si trae cajaAbierta entra
            if (!empty($cajaAbierta)) {
                $entity->setCaja($cajaAbierta[0]);
                $em->persist($entity);
                $em->flush();
                $this->get('session')->getFlashBag()->add('success', 'flash.create.success');
                
                if ($form->get('saveAndAdd')->isClicked()) {
                    $numero = $entity->getNumero();
                    $form->getData()->setNumero($numero + 1);
                    $nextAction = $this->generateUrl('admin_facturaventa_new', array('tipo' => $entity->getTipo(), 'proceso' => $entity->getProceso()->getId()));
                } else {
                    $nextAction = $this->generateUrl('admin_facturaventa_show', array('id' => $entity->getId()));
                }
                
                return $this->redirect($nextAction);
            } else {
                $this->get('session')->getFlashBag()->add('danger', 'No hay ninguna Caja Abierta');
            }
        } else {
            $errores = $form->getErrors();

            if (!empty($errores)) {
                $this->get('session')->getFlashBag()->add('danger', $errores[0]->getMessage());
            } else {
                $this->get('session')->getFlashBag()->add('danger', 'flash.create.error');
            }
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a form to create a FacturaVenta entity.
     *
     * @param FacturaVenta $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(FacturaVenta $entity) {
        $form = $this->createForm(new FacturaVentaType(), $entity, array(
            'action' => $this->generateUrl('admin_facturaventa_create'),
            'method' => 'POST',
        ));

        $form
            ->add('save', 'submit', array(
                'translation_domain' => 'MWSimpleCrudGeneratorBundle',
                'label' => 'views.new.save',
                'attr' => array('class' => 'btn btn-success col-lg-2')
            ))
            ->add('saveAndAdd', 'submit', array(
                'translation_domain' => 'MWSimpleCrudGeneratorBundle',
                'label' => 'views.new.saveAndAdd',
                'attr' => array('class' => 'btn btn-primary col-lg-2 col-lg-offset-1')
            ))
        ;

        return $form;
    }

    /**
     * Displays a form to create a new FacturaVenta entity.
     *
     * @Route("/new/{tipo}/{proceso}", name="admin_facturaventa_new", options={"expose"=true})
     * @Method("GET")
     * @Template()
     */
    public function newAction($tipo, $proceso) {
        $this->get('security_role')->controlRolesUser();
        $entity = new FacturaVenta();
        $entity->setTipo($tipo);
        $em = $this->getDoctrine()->getManager();
        $ultimoNumero = $em->getRepository('SistemaFACTURACIONBundle:FacturaVenta')->findUltimoNumero($tipo);
        if (!empty($ultimoNumero)) {
            $entity->setNumero($ultimoNumero[0]['numero'] + 1);
        } else {
            $entity->setNumero(1);
        }
        //agrego cuentas segun proceso
        $procesoService = $this->get('proceso');
        $entityProceso  = $procesoService->create($entity, $proceso);
        $entity->setProceso($entityProceso);
        //fin agrego
        $form = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a FacturaVenta entity.
     *
     * @Route("/{id}", name="admin_facturaventa_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id) {
        $this->get('security_role')->controlRolesUser();

src/Sistema/FACTURACIONBundle/Resources/views/FacturaVenta/edit.html.twig
{% extends 'MWSimpleCrudGeneratorBundle::layout.html.twig' %}

{% block title %}
{{ parent() }} - {{ 'views.edit.edit'|trans({'%entity%': 'FacturaVenta'}, 'MWSimpleCrudGeneratorBundle') }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/sistemamwsform/select2/select2.css') }}">
    <script src="{{ asset('bundles/sistemamwsform/select2/select2.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsform/datetime/js/bootstrap-datetimepicker.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsform/datetime/js/locales/bootstrap-datetimepicker.es.js') }}"></script>
    <link id="bootstrap-style" href="{{ asset('bundles/sistemamwsform/extend/css/jasny-bootstrap.min.css') }}" rel="stylesheet">
{% endblock %}
    
{% block page %}
    {% form_theme edit_form 'SistemaFACTURACIONBundle:Form:form-facturaventa-theme-edit.html.twig' %}

    <div class="panel panel-default center-block">
        <div class="panel-heading">
            <h3 class="panel-title center-block">
                Factura de Venta
            </h3>
        </div>
            
        <div class="panel-body">
            {{ form(edit_form) }}
        </div>
    </div>
        <div class="col-lg-9">
    <div class="float-left col-lg-3">
        <a class="btn btn-info col-lg-11" href="{{ path('admin_facturaventa') }}">
            {{ 'views.recordactions.backtothelist'|trans({}, 'MWSimpleCrudGeneratorBundle') }}
        </a>
    </div>
    <div class="float-left col-lg-3">{{ form(delete_form) }}</div>
</div>
{% endblock %}

{% block javascript %}
    {{ parent() }}
    <script src="{{ asset('bundles/mwsimplecrudgenerator/js/widget.js') }}"></script>
    <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
    <script src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>
    <script src="{{ asset('bundles/sistemastock/js/cliente.js') }}"></script>
    <script src="{{ asset('bundles/sistemastock/js/ajaxElementOnSelected.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsconf/js/addForm.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsconf/js/addFormEmbed.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsform/extend/js/jasny-bootstrap.min.js') }}"></script>
{% endblock %}

src/Sistema/FACTURACIONBundle/Resources/views/FacturaVenta/index.html.twig
{% extends 'MWSimpleCrudGeneratorBundle::layout.html.twig' %}

{% block title %}
    {{ parent() }} - {{ 'views.index.list'|trans({'%entity%': 'FacturaVenta'}, 'MWSimpleCrudGeneratorBundle') }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/sistemamwsform/select2/select2.css') }}">
    <script src="{{ asset('bundles/sistemamwsform/select2/select2.min.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsform/datetime/js/bootstrap-datetimepicker.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsform/datetime/js/locales/bootstrap-datetimepicker.es.js') }}"></script>
    <link id="bootstrap-style" href="{{ asset('bundles/sistemamwsform/extend/css/jasny-bootstrap.min.css') }}" rel="stylesheet">
{% endblock %}

{% block page %}
    <div class="row">
        <div class="col-lg-2">
            {% if filterForm.vars.errors|length > 0 %}
                <div class="alert alert-block alert-danger fade in form-errors">
                    {{ form_errors(filterForm) }}
                </div>
            {% endif %}
            &nbsp;
        </div>
        <div class="col-lg-12">
            <div class="filters-right">
                <a class="btn btn-primary dropdown-toggle" data-toggle="collapse" data-target="#filters">
                    {{ 'views.index.filters'|trans({}, 'MWSimpleCrudGeneratorBundle') }}
                    <span class="caret"></span>
                </a>
            </div>
        </div>

        <div class="col-lg-12">
            <div id="filters" class="well collapse">
                <div class="form-group">
                    {{ form(filterForm) }}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading"><h3>Facturas de Ventas</h3></div>    
            <div class="panel-body">
                <table class="table table-striped table-bordered table-condensed table-responsive">
                    <thead>
                        <tr>
                            {% if is_granted('ROLE_SUPER_ADMIN') %}
                                <th{% if entities.isSorted('a.Id') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(entities, 'Id', 'a.id') }}</th>
                                {% endif %}
                            <th{% if entities.isSorted('a.Tipo') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(entities, 'Tipo', 'a.tipo') }}</th>
                            <th{% if entities.isSorted('a.Numero') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(entities, 'Numero', 'a.numero') }}</th>
                            <th{% if entities.isSorted('a.Fecha') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(entities, 'Fecha', 'a.fecha') }}</th>
                            <th{% if entities.isSorted('a.Descripcion') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(entities, 'Descripcion', 'a.descripcion') }}</th>
                            <th{% if entities.isSorted('a.Monto') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(entities, 'Monto', 'a.monto') }}</th>
                            <th{% if entities.isSorted('a.Anulado') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(entities, 'Estado', 'a.anulado') }}</th>
                            {#
                            <th{% if entities.isSorted('a.Formapago') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(entities, 'Forma de Pago', 'a.formaPago') }}</th>
                            #}
                            <th>{{ 'views.index.actions'|trans({}, 'MWSimpleCrudGeneratorBundle') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entity in entities %}
                            <tr>
                                {% if is_granted('ROLE_SUPER_ADMIN') %}
                                    <td><a href="{{ path('admin_facturaventa_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                                    {% endif %}
                                <td>{{ entity.tipo }}</td>
                                <td>{{ entity.numero }}</td>
                                <td>{% if entity.fecha %}{{ entity.fecha|date('d/m/Y') }}{% endif %}</td>
                                <td>{{ entity.ordenDescripcion }}</td>
                                <td>${{ entity.monto }}</td>
                                <td>{{ entity.anulado ? isActive(false, '', 'Anulada' ) : isActive(true, '', 'Anulada' ) }}</td>
                                {#
                                <td>{{ entity.formaPago }}</td>
                                #}
                                <td>
                                    <a class="glyphicon glyphicon-search tooltips"  href="{{ path('admin_facturaventa_show', { 'id': entity.id }) }}" title="" rel="tooltip" data-original-title="{{ 'views.actions.show'|trans({}, 'MWSimpleCrudGeneratorBundle') }}">
                                    </a>
                                    <a class="glyphicon glyphicon-edit tooltips"  href="{{ path('admin_facturaventa_edit', { 'id': entity.id }) }}" title="" rel="tooltip" data-original-title="{{ 'views.actions.edit'|trans({}, 'MWSimpleCrudGeneratorBundle') }}">
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="panel-footer"> 
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-lg-push-3 col-md-push-3">
                        <label for="proceso">Seleccione Proceso</label>
                        <input id="proceso" type="hidden">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 navigation">
            {{ knp_pagination_render(entities) }}
        </div>
        <br>
        <div class="col-lg-8"> 
            <a class="btn btn-primary likepaginator btnNew"  data-tipo="B" href="javascript:;" {#href="{{ path('admin_facturaventa_new', { 'tipo': "B" }) }}"#}>
                {{ 'views.index.createnew'|trans({}, 'MWSimpleCrudGeneratorBundle') }} Factura de Venta B
            </a>
            <a class="btn btn-primary likepaginator btnNew"  data-tipo="A" href="javascript:;"{#href="{{ path('admin_facturaventa_new', { 'tipo': "A" }) }}"#}>
                {{ 'views.index.createnew'|trans({}, 'MWSimpleCrudGeneratorBundle') }} Factura de Venta A
            </a>
        </div>
    </div>
    {% include 'SistemaMWSFORMBundle:Default:modalAlert.html.twig' %}
{% endblock %}

{% block javascript %}
    {{parent()}}
    <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
    <script src="{{ path('fos_js_routing_js', {'callback': 'fos.Router.setData'}) }}"></script>

    <script type="text/javascript">
        $('.tooltips').tooltip();
        var url = "admin_facturaventa_new";
        $(document).ready(function () {

            $("#sistema_facturacionbundle_facturaventafiltertype_fecha").datetimepicker({
                format: 'yyyy-mm-dd',
                language: 'es',
                minView: 2
            });
        });

    </script>
    <script src="{{ asset('bundles/sistemaplandecuentas/js/selectProceso.js') }}"></script>
{% endblock %}

src/Sistema/FACTURACIONBundle/Resources/views/FacturaVenta/new.html.twig
{% extends 'MWSimpleCrudGeneratorBundle::layout.html.twig' %}

{% block title %}
{{ parent() }} - {{ 'views.new.creation'|trans({'%entity%': 'FacturaVenta'}, 'MWSimpleCrudGeneratorBundle') }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/sistemamwsform/select2/select2.css') }}">
    <script src="{{ asset('bundles/sistemamwsform/select2/select2.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsform/datetime/js/bootstrap-datetimepicker.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsform/datetime/js/locales/bootstrap-datetimepicker.es.js') }}"></script>
    <link id="bootstrap-style" href="{{ asset('bundles/sistemamwsform/extend/css/jasny-bootstrap.min.css') }}" rel="stylesheet">
{% endblock %}
    
{% block page %}
    {% form_theme form 'SistemaFACTURACIONBundle:Form:form-facturaventa-theme.html.twig' %}
    <div class="panel panel-default center-block">
        <div class="panel-heading">
            <h3 class="panel-title center-block">
                Factura de Venta
            </h3>
        </div>
            
        <div class="panel-body">
            {{ form(form) }}
        </div>
    </div>

    <div class="col-lg-9">
        <div class="float-left col-lg-3">
            <a class="btn btn-info col-lg-11" href="{{ path('admin_facturaventa') }}">
                {{ 'views.recordactions.backtothelist'|trans({}, 'MWSimpleCrudGeneratorBundle') }}
            </a>
        </div>
    </div>
{% endblock %}
    
{% block javascript %}
    {{ parent() }}
    <script src="{{ asset('bundles/mwsimplecrudgenerator/js/widget.js') }}"></script>
    <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
    <script src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>
    <script src="{{ asset('bundles/sistemastock/js/cliente.js') }}"></script>
    <script src="{{ asset('bundles/sistemastock/js/ajaxElementOnSelected.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsconf/js/addForm.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsconf/js/addFormEmbed.js') }}"></script>
    <script src="{{ asset('bundles/sistemamwsform/extend/js/jasny-bootstrap.min.js') }}"></script>
{% endblock %}